# Generated by Django 4.1.3 on 2022-11-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0002_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='total_price',
            field=models.CharField(default='550', max_length=250),
            preserve_default=False,
        ),
    ]
