# Generated by Django 4.1.3 on 2022-11-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0003_command_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='total_quantity_products',
            field=models.CharField(default='600', max_length=300),
            preserve_default=False,
        ),
    ]
