# Generated by Django 4.1.3 on 2022-11-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0004_command_total_quantity_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='total_price',
            new_name='totalPrice',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='total_quantity_products',
            new_name='totalQuantity',
        ),
    ]
