# Generated by Django 4.1.3 on 2022-11-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0005_rename_total_price_command_totalprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000)),
                ('date_command', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
