# Generated by Django 4.1.3 on 2022-11-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_command',
            new_name='date_comment',
        ),
    ]
