# Generated by Django 4.1.3 on 2022-11-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0008_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Customer_name', max_length=200),
            preserve_default=False,
        ),
    ]
